var THUMB_MAP = {
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/518X0B5HyL.jpg": "assets/thumbs/af128e4e55ec.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/61OvlyCCTL.jpg": "assets/thumbs/98b06687ef6c.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/61VE37EBeL.jpg": "assets/thumbs/d08d273f1645.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/615s2rJBdzL._AC_SL1000_.jpg": "assets/thumbs/f06a4c466b5a.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/61u0vcRXq1L._AC_SL1000_.jpg": "assets/thumbs/71f36d1a47cb.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/61ukrptug9L._AC_SL1000_.jpg": "assets/thumbs/d53a2931ca72.jpg",
  "4Pcs Mud guard Fit for JETOUR T2 Front and Rear Splash Guards/71kuuco8CqL._AC_SL1500_.jpg": "assets/thumbs/8ae502eec2dc.jpg",
  "Automotive 318 Ambient Lighting for Chery Jetour T2 & Jetour T2 PHEV/4_6bd5af70-49e4-4adf-8306-f2f32c8e7128_720x.jpg": "assets/thumbs/014b19cd1ebc.jpg",
  "Automotive 318 Ambient Lighting for Chery Jetour T2 & Jetour T2 PHEV/66_cf63fb6b-9524-4dc1-a82e-0f4ee54a6357_1800x1800.webp": "assets/thumbs/0f1aacacb1e2.jpg",
  "Automotive 318 Ambient Lighting for Chery Jetour T2 & Jetour T2 PHEV/8_ec135337-b9ed-4b8c-9fdb-257f85e6b1da_1800x1800.webp": "assets/thumbs/92cec09546aa.jpg",
  "Automotive 318 Ambient Lighting for Chery Jetour T2 & Jetour T2 PHEV/9_c3d54028-1ae9-44a9-844f-be9971ce947d_1800x1800.webp": "assets/thumbs/74c6e82ace75.jpg",
  "Brake Caliper Cover Jetour ROX 01/jetour-rox-01-brake-caliper-cover-colors.png": "assets/thumbs/85038dbfd0ef.jpg",
  "Brake Caliper Cover Jetour T2/2ff5dfab-51bc-4a9f-b953-e2a6f6ff037a.jpg": "assets/thumbs/bc29f5f5268b.jpg",
  "Brake Caliper Cover Jetour T2/57_a3094dd3-dcb6-432a-8ead-4b014a85dd09.webp": "assets/thumbs/aa48c7eaac46.jpg",
  "Brake Caliper Cover Jetour T2/58_ad3c7463-9b27-453a-b0ac-4b9d40c04f09.webp": "assets/thumbs/8b69fb395fb1.jpg",
  "Central Control Pad Jetour T2/before-after.jpg": "assets/thumbs/9255a5dd095a.jpg",
  "Central Control Pad Jetour T2/installed-orange.jpg": "assets/thumbs/0b27a002d585.jpg",
  "Central Control Pad Jetour T2/installed-white.jpg": "assets/thumbs/bb6b1374a565.jpg",
  "Central Control Pad Jetour T2/parts-layout.jpg": "assets/thumbs/a5c5202ecd47.jpg",
  "Central Control Pad Jetour T2/variant-black.jpg": "assets/thumbs/a5df4829dfaa.jpg",
  "Central Control Pad Jetour T2/variant-orange.jpg": "assets/thumbs/c238b43ea5a2.jpg",
  "Central Control Pad Jetour T2/variant-white.jpg": "assets/thumbs/99a4cd599148.jpg",
  "Crystal Gear Lever Handle Jetour T2/jetour-t2-crystal-gear-lever-handle-front.jpg": "assets/thumbs/6847d793f130.jpg",
  "Crystal Gear Lever Handle Jetour T2/jetour-t2-crystal-gear-lever-handle-installed.jpg": "assets/thumbs/d56f7fa3f702.jpg",
  "Dash Cam Mirror Jetour T2/dashcam-mirror-1.jpg": "assets/thumbs/2c0a0a57a4d6.jpg",
  "Dash Cam Mirror Jetour T2/dashcam-mirror-2.jpg": "assets/thumbs/7c8e5b5f3c8a.jpg",
  "Dash Cam Mirror Jetour T2/dashcam-mirror-3.jpg": "assets/thumbs/9e2d1c4b7a63.jpg",
  "Dash Cam Mirror Jetour T2/dashcam-mirror-4.jpg": "assets/thumbs/1a3d5c8e9f02.jpg",
  "Defender Style Headlights Jetour T2/headlights-1.jpg": "assets/thumbs/def1.jpg",
  "Defender Style Headlights Jetour T2/headlights-2.jpg": "assets/thumbs/def2.jpg",
  "Defender Style Headlights Jetour T2/headlights-3.jpg": "assets/thumbs/def3.jpg",
  "Defender Style Tail Lights Jetour T2/tail-lights-1.jpg": "assets/thumbs/tl1.jpg",
  "Defender Style Tail Lights Jetour T2/tail-lights-2.jpg": "assets/thumbs/tl2.jpg",
  "Defender Style Tail Lights Jetour T2/tail-lights-3.jpg": "assets/thumbs/tl3.jpg",
  "Fog Light Jetour T2/jetour-t2-fog-light-front-view.webp": "assets/thumbs/fog1.webp",
  "Fog Light Jetour T2/jetour-t2-fog-light-installed.webp": "assets/thumbs/fog2.webp",
  "HR Wheel Spacer Jetour T2/wheel-spacer-1.jpg": "assets/thumbs/ws1.jpg",
  "HR Wheel Spacer Jetour T2/wheel-spacer-2.jpg": "assets/thumbs/ws2.jpg",
  "HR Wheel Spacer Jetour T2/wheel-spacer-3.jpg": "assets/thumbs/ws3.jpg",
  "Interior Door Handle Protectors for Jetour T2 & Chery Jetour T2 PHEV/22_665831f9-3d6a-4f65-83cb-b1788dcc32f1_1800x1800.webp": "assets/thumbs/handle1.webp",
  "Interior Door Handle Protectors for Jetour T2 & Chery Jetour T2 PHEV/23_04632e01-7905-4153-9797-f1bd80d813af_720x.webp": "assets/thumbs/handle2.webp",
  "Interior Door Handle Protectors for Jetour T2 & Chery Jetour T2 PHEV/24_1c7cd893-69bf-40fd-90f2-157574031524_1800x1800.webp": "assets/thumbs/handle3.webp",
  "Interior Door Handle Protectors for Jetour T2 & Chery Jetour T2 PHEV/26_1725b773-ab70-45b2-be6e-4cd4b27a9126_720x.webp": "assets/thumbs/handle4.webp",
  "Jetour T2 mud flaps/mud-flap-1.webp": "assets/thumbs/mf1.webp",
  "Jetour T2 mud flaps/mud-flap-2.webp": "assets/thumbs/mf2.webp",
  "Jetour T2 mud flaps/mud-flap-3.webp": "assets/thumbs/mf3.webp",
  "Jetour T2 mud flaps/mud-flap-4.webp": "assets/thumbs/mf4.webp",
  "Key Cover Jetour T2/key-cover-1.jpg": "assets/thumbs/kc1.jpg",
  "Key Cover Jetour T2/key-cover-2.jpg": "assets/thumbs/kc2.jpg",
  "Mud Flaps Jetour ROX 01/rox-mud-flap-1.webp": "assets/thumbs/rmf1.webp",
  "Mud Flaps Jetour ROX 01/rox-mud-flap-2.webp": "assets/thumbs/rmf2.webp",
  "Phone Holder Jetour ROX 01/phone-holder-rox-1.jpg": "assets/thumbs/phr1.jpg",
  "Phone Holder Jetour ROX 01/phone-holder-rox-2.jpg": "assets/thumbs/phr2.jpg",
  "Phone Holder Jetour T2/phone-holder-t2-1.jpg": "assets/thumbs/pht1.jpg",
  "Phone Holder Jetour T2/phone-holder-t2-2.jpg": "assets/thumbs/pht2.jpg",
  "Rear Bumper Steel Tow Bar for Jetour T2 Accessories Factory Direct Trailer Bar Popular Exterior Car Accessories Hot Sa./tow-bar-1.jpg": "assets/thumbs/tb1.jpg",
  "Rear Bumper Steel Tow Bar for Jetour T2 Accessories Factory Direct Trailer Bar Popular Exterior Car Accessories Hot Sa./tow-bar-2.jpg": "assets/thumbs/tb2.jpg",
  "Rear Fender Liner Jetour ROX 01/rox-fender-1.jpg": "assets/thumbs/rf1.jpg",
  "Rear Fender Liner Jetour ROX 01/rox-fender-2.jpg": "assets/thumbs/rf2.jpg",
  "Rear Number Plate Cover Jetour ROX 01/number-plate-cover-1.jpg": "assets/thumbs/npc1.jpg",
  "Rear Spoiler for Jetour Traveler T2 2023-2024/spoiler-t2-1.jpg": "assets/thumbs/sp1.jpg",
  "Rear Spoiler for Jetour Traveler T2 2023-2024/spoiler-t2-2.jpg": "assets/thumbs/sp2.jpg",
  "Rear Spoiler Wing Fit For Jetour T2 Traveller 2023 2024/spoiler-2-1.jpg": "assets/thumbs/sp3.jpg",
  "Rear Spoiler Wing Fit For Jetour T2 Traveller 2023 2024/spoiler-2-2.jpg": "assets/thumbs/sp4.jpg",
  "Rims Jetour ROX 01/rim-rox-1.jpg": "assets/thumbs/rr1.jpg",
  "Rims Jetour ROX 01/rim-rox-2.jpg": "assets/thumbs/rr2.jpg",
  "Rims Jetour T2/rim-t2-1.jpg": "assets/thumbs/rt1.jpg",
  "Rims Jetour T2/rim-t2-2.jpg": "assets/thumbs/rt2.jpg",
  "ROX 01 Badge Emblem/rox-badge-1.jpg": "assets/thumbs/rb1.jpg",
  "ROX 01 Badge Emblem/rox-badge-2.jpg": "assets/thumbs/rb2.jpg",
  "Screen Protector Jetour ROX 01/screen-protector-rox-1.jpg": "assets/thumbs/spr1.jpg",
  "Screen Protector Jetour ROX 01/screen-protector-rox-2.jpg": "assets/thumbs/spr2.jpg",
  "Screen Protector Jetour T2/screen-protector-t2-1.jpg": "assets/thumbs/spt1.jpg",
  "Screen Protector Jetour T2/screen-protector-t2-2.jpg": "assets/thumbs/spt2.jpg",
  "Side Ambient Light Panel Dubai Edition Jetour T2/dubai-panel-1.jpg": "assets/thumbs/dp1.jpg",
  "Side Ambient Light Panel Dubai Edition Jetour T2/dubai-panel-2.jpg": "assets/thumbs/dp2.jpg",
  "Side Ladder for Jetour Traveler T2 2023-2024/ladder-1.jpg": "assets/thumbs/ld1.jpg",
  "Side Ladder for Jetour Traveler T2 2023-2024/ladder-2.jpg": "assets/thumbs/ld2.jpg",
  "Spare Tire Cover Jetour T2/spare-cover-1.jpg": "assets/thumbs/sc1.jpg",
  "Spare Tire Cover Jetour T2/spare-cover-2.jpg": "assets/thumbs/sc2.jpg",
  "Spoiler Jetour ROX 01/spoiler-rox-1.jpg": "assets/thumbs/sr1.jpg",
  "Spoiler Jetour ROX 01/spoiler-rox-2.jpg": "assets/thumbs/sr2.jpg",
  "Under Seats Cover Jetour T2/under-seat-cover-1.jpg": "assets/thumbs/us1.jpg",
  "Under Seats Cover Jetour T2/under-seat-cover-2.jpg": "assets/thumbs/us2.jpg",
  "Car Mat 2 Ply Jetour T2/car-mat-2ply-1.jpg": "assets/thumbs/cm21.jpg",
  "Car Mat 2 Ply Jetour T2/car-mat-2ply-2.jpg": "assets/thumbs/cm22.jpg",
  "Car Mat Jetour ROX 01/car-mat-rox-1.jpg": "assets/thumbs/cmr1.jpg",
  "Car Mat Jetour ROX 01/car-mat-rox-2.jpg": "assets/thumbs/cmr2.jpg",
  "Car Mat Jetour T2/car-mat-t2-1.jpg": "assets/thumbs/cm1.jpg",
  "Car Mat Jetour T2/car-mat-t2-2.jpg": "assets/thumbs/cm2.jpg",
  "Original Brake Pad Jetour T2/brake-pad-1.jpg": "assets/thumbs/bp1.jpg",
  "Original Brake Pad Jetour T2/brake-pad-2.jpg": "assets/thumbs/bp2.jpg",
  "Original Spare Tire Cover Jetour T2/orig-spare-cover-1.jpg": "assets/thumbs/osc1.jpg",
  "Original Spare Tire Cover Jetour T2/orig-spare-cover-2.jpg": "assets/thumbs/osc2.jpg",
  "Side Storage Box for Jetour Traveler T2 2023-2024/storage-box-1.jpg": "assets/thumbs/sb1.jpg",
  "Side Storage Box for Jetour Traveler T2 2023-2024/storage-box-2.jpg": "assets/thumbs/sb2.jpg"
};

function getThumb(path) {
  return THUMB_MAP[path] || path;
}
window.getThumb = getThumb;
